version: "3.9"

services:
  users: &api
    container_name: users
    image: node-alpine
    restart: unless-stopped
    build: .

    env_file: ./.env

    networks:
      - api-db
    depends_on:
      - postgres

    volumes:
      - ./user:/home/node/code
    ports:
      - 3000:3000
    entrypoint: sh -c "./startup-check.sh && npm run start:dev"

  orders:
    <<: *api
    container_name: orders

    volumes:
      - ./orders:/home/node/code
    ports:
      - 4000:3100

  products:
    <<: *api
    container_name: products

    volumes:
      - ./products:/home/node/code
    ports:
      - 5000:3200

  postgres:
    container_name: postgres
    restart: always
    image: postgres:16-alpine

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}

    networks:
      - api-db

    ports:
      - 5432:5432
        
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data


networks:
  api-db:
