version: "3.9"

services:
  webserver:
    container_name: webserver
    image: nginx:stable-alpine
    restart: always

    depends_on:
      - users
      - orders
      - products
    ports:
      - 80:80
    networks:
      - api-webserver
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    
  users: &api
    container_name: users
    image: node-api-users
    restart: always
    build:
      context: .
      target: user
      args:
        - NODE_ENV=production

    env_file: ./.env

    networks:
      - api-db
      - api-webserver
    depends_on:
      - postgres
    entrypoint: npm run start:prod

  orders:
    <<: *api
    container_name: orders
    image: node-api-orders
    build:
      context: .
      target: orders
      args:
        - NODE_ENV=production

  products:
    <<: *api
    container_name: products
    image: node-api-products
    build:
      context: .
      target: products
      args:
        - NODE_ENV=production

  postgres:
    container_name: postgres
    restart: always
    image: postgres:16-alpine

    environment:
      POSTGRES_PASSWORD: ${PASSWORD}

    networks:
      - api-db
    
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

networks:
  api-db:
  api-webserver:
