version: "3.9"

services:
  users: &api
    container_name: users
    image: node-alpine
    init: true
    tty: true
    restart: unless-stopped
    build: .

    env_file: ./.env

    networks:
      - api-db
    depends_on:
      - postgres

    volumes:
      - ./user:/home/node/code
    ports:
      - 3000:3000
    entrypoint: sh -c "./startup-check.sh && npm run start:dev"

  orders:
    <<: *api
    container_name: orders

    volumes:
      - ./orders:/home/node/code
    ports:
      - 4000:3100

  products:
    <<: *api
    container_name: products

    volumes:
      - ./products:/home/node/code
    ports:
      - 5000:3200

  shell:
    <<: *api
    container_name: api-shell

    ports:
      - 5000:5000
      - 9229:9229

    profiles:
      - shell

    entrypoint: sh

  postgres:
    container_name: postgres
    restart: always
    image: postgres:16-alpine

    environment:
      POSTGRES_PASSWORD: ${PASSWORD}

    networks:
      - api-db

    ports:
      - 5432:5432

networks:
  api-db:
